"""add matching tables

Revision ID: 57f58bcfd7d3
Revises: 7e78e0d5a3f5
Create Date: 2025-11-19 00:25:12.654007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f58bcfd7d3'
down_revision: Union[str, Sequence[str], None] = '7e78e0d5a3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: users and auth_users tables already exist, so we only create matching tables
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['yolk_staging.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='yolk_staging'
    )
    op.create_index(op.f('ix_yolk_staging_groups_created_by_id'), 'groups', ['created_by_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_groups_id'), 'groups', ['id'], unique=False, schema='yolk_staging')
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'member'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['yolk_staging.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['yolk_staging.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member'),
    schema='yolk_staging'
    )
    op.create_index('idx_group_members_group', 'group_members', ['group_id'], unique=False, schema='yolk_staging')
    op.create_index('idx_group_members_user', 'group_members', ['user_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_group_members_group_id'), 'group_members', ['group_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_group_members_id'), 'group_members', ['id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_group_members_user_id'), 'group_members', ['user_id'], unique=False, schema='yolk_staging')
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_group_id', sa.Integer(), nullable=False),
    sa.Column('likee_group_id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.UUID(), nullable=True),
    sa.Column('group_b_approvals_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_b_required_count', sa.Integer(), nullable=False),
    sa.Column('group_a_approvals_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_a_required_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending_group_b'"), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['yolk_staging.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['likee_group_id'], ['yolk_staging.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_group_id'], ['yolk_staging.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liker_group_id', 'likee_group_id', name='uq_like'),
    schema='yolk_staging'
    )
    op.create_index('idx_likes_likee', 'likes', ['likee_group_id', 'status'], unique=False, schema='yolk_staging')
    op.create_index('idx_likes_liker', 'likes', ['liker_group_id', 'status'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_likes_id'), 'likes', ['id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_likes_initiator_user_id'), 'likes', ['initiator_user_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_likes_likee_group_id'), 'likes', ['likee_group_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_likes_liker_group_id'), 'likes', ['liker_group_id'], unique=False, schema='yolk_staging')
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group1_id', sa.Integer(), nullable=False),
    sa.Column('group2_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('group1_id < group2_id', name='check_match_order'),
    sa.ForeignKeyConstraint(['group1_id'], ['yolk_staging.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group2_id'], ['yolk_staging.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group1_id', 'group2_id', name='uq_match'),
    schema='yolk_staging'
    )
    op.create_index('idx_matches_group1', 'matches', ['group1_id', 'matched_at'], unique=False, schema='yolk_staging')
    op.create_index('idx_matches_group2', 'matches', ['group2_id', 'matched_at'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_matches_group1_id'), 'matches', ['group1_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_matches_group2_id'), 'matches', ['group2_id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_matches_id'), 'matches', ['id'], unique=False, schema='yolk_staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yolk_staging_matches_id'), table_name='matches', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_matches_group2_id'), table_name='matches', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_matches_group1_id'), table_name='matches', schema='yolk_staging')
    op.drop_index('idx_matches_group2', table_name='matches', schema='yolk_staging')
    op.drop_index('idx_matches_group1', table_name='matches', schema='yolk_staging')
    op.drop_table('matches', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_likes_liker_group_id'), table_name='likes', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_likes_likee_group_id'), table_name='likes', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_likes_initiator_user_id'), table_name='likes', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_likes_id'), table_name='likes', schema='yolk_staging')
    op.drop_index('idx_likes_liker', table_name='likes', schema='yolk_staging')
    op.drop_index('idx_likes_likee', table_name='likes', schema='yolk_staging')
    op.drop_table('likes', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_group_members_user_id'), table_name='group_members', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_group_members_id'), table_name='group_members', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_group_members_group_id'), table_name='group_members', schema='yolk_staging')
    op.drop_index('idx_group_members_user', table_name='group_members', schema='yolk_staging')
    op.drop_index('idx_group_members_group', table_name='group_members', schema='yolk_staging')
    op.drop_table('group_members', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_groups_id'), table_name='groups', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_groups_created_by_id'), table_name='groups', schema='yolk_staging')
    op.drop_table('groups', schema='yolk_staging')
    # Note: Don't drop users and auth_users tables in downgrade
    # ### end Alembic commands ###
