"""init yolk_staging schema

Revision ID: 8675288e9cf7
Revises: 
Create Date: 2025-11-11 18:02:24.335255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8675288e9cf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS yolk_staging"))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('pictures', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='yolk_staging'
    )
    op.create_index(op.f('ix_yolk_staging_users_email'), 'users', ['email'], unique=True, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_users_id'), 'users', ['id'], unique=False, schema='yolk_staging')
    op.create_index(op.f('ix_yolk_staging_users_phone_number'), 'users', ['phone_number'], unique=True, schema='yolk_staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yolk_staging_users_phone_number'), table_name='users', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_users_id'), table_name='users', schema='yolk_staging')
    op.drop_index(op.f('ix_yolk_staging_users_email'), table_name='users', schema='yolk_staging')
    op.drop_table('users', schema='yolk_staging')
    op.execute(sa.text("DROP SCHEMA IF EXISTS yolk_staging CASCADE"))
    # ### end Alembic commands ###
